//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hashing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;lblversion&quot;: &quot;版本: {VN}&quot;,
        ///	&quot;btnFindIdenticals&quot;: &quot;查找相同的&quot;,
        ///	&quot;btnCompare&quot;: &quot;比较&quot;,
        ///	&quot;btnSaveJson&quot;: &quot;另存为JSON&quot;,
        ///	&quot;btnOptions&quot;: &quot;选项&quot;,
        ///	&quot;btnUpdate&quot;: &quot;更新&quot;,
        ///	&quot;btnCalculate&quot;: &quot;计算&quot;,
        ///	&quot;lblCalculating&quot;: &quot;将文件拖放到此处...&quot;,
        ///	&quot;lblCalculatingNow&quot;: &quot;计算中...&quot;,
        ///	&quot;btnCancelHashing&quot;: &quot;取消&quot;,
        ///	&quot;btnCancelHashingPressed&quot;: &quot;取消中...&quot;,
        ///	&quot;button7&quot;: &quot;确定&quot;,
        ///	&quot;label3&quot;: &quot;选择语言&quot;,
        ///	&quot;btnPaste&quot;: &quot;粘贴&quot;,
        ///	&quot;chkRemove&quot;: &quot;移除短横线&quot;,
        ///	&quot;label2&quot;: &quot;结果&quot;,
        ///	&quot;lblNoMatch&quot;: &quot;没有匹配的文件&quot;,
        ///	&quot;label77&quot;: &quot;JSON文件被检测到. 你想用它来做什么?&quot;,
        ///	&quot;btnCalc&quot;: &quot;计算文件哈希值&quot;,
        ///	&quot;btnAn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;lblversion&quot;: &quot;Version: {VN}&quot;,
        ///	&quot;btnFindIdenticals&quot;: &quot;Identische finden&quot;,
        ///	&quot;btnCompare&quot;: &quot;Vergleichen&quot;,
        ///	&quot;btnSaveJson&quot;: &quot;Als JSON speichern&quot;,
        ///	&quot;btnOptions&quot;: &quot;Optionen&quot;,
        ///	&quot;btnUpdate&quot;: &quot;Aktualisieren&quot;,
        ///	&quot;btnCalculate&quot;: &quot;Berechnen&quot;,
        ///	&quot;lblCalculating&quot;: &quot;Dateien hierhin ziehen und ablegen...&quot;,
        ///	&quot;lblCalculatingNow&quot;: &quot;Berechne...&quot;,
        ///	&quot;btnCancelHashing&quot;: &quot;Abbrechen&quot;,
        ///	&quot;btnCancelHashingPressed&quot;: &quot;Breche ab...&quot;,
        ///	&quot;button7&quot;: &quot;OK&quot;,
        ///	&quot;label1&quot;: &quot;erwarteter Hashwert:&quot;,
        ///	&quot;btnPaste&quot;: &quot;Einfügen&quot;,
        ///	&quot;chkRemove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;lblversion&quot;: &quot;Έκδοση: {VN}&quot;,
        ///	&quot;btnFindIdenticals&quot;: &quot;Έυρεση ίδιων αρχείων&quot;,
        ///	&quot;btnCompare&quot;: &quot;Σύγκριση&quot;,
        ///	&quot;btnSaveJson&quot;: &quot;Αποθήκευση JSON&quot;,
        ///	&quot;btnOptions&quot;: &quot;Ρυθμίσεις&quot;,
        ///	&quot;btnUpdate&quot;: &quot;Ενημέρωση&quot;,
        ///	&quot;btnCalculate&quot;: &quot;Υπολογισμός&quot;,
        ///	&quot;lblCalculating&quot;: &quot;Σύρετε αρχεία εδω...&quot;,
        ///	&quot;lblCalculatingNow&quot;: &quot;Υπολογισμός...&quot;,
        ///	&quot;btnCancelHashing&quot;: &quot;Ακύρωση&quot;,
        ///	&quot;btnCancelHashingPressed&quot;: &quot;Ακύρωση...&quot;,
        ///	&quot;button7&quot;: &quot;Εντάξει&quot;,
        ///	&quot;label1&quot;: &quot;Αναμενόμενο hash:&quot;,
        ///	&quot;btnPaste&quot;: &quot;Επικόλληση&quot;,
        ///	&quot;chkRemove&quot;: &quot;Αφαίρεση παύλας [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EL {
            get {
                return ResourceManager.GetString("EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;lblversion&quot;: &quot;Version: {VN}&quot;,
        ///	&quot;btnFindIdenticals&quot;: &quot;Find Identicals&quot;,
        ///	&quot;btnCompare&quot;: &quot;Compare&quot;,
        ///	&quot;btnSaveJson&quot;: &quot;Save as JSON&quot;,
        ///	&quot;btnOptions&quot;: &quot;Options&quot;,
        ///	&quot;btnUpdate&quot;: &quot;Update&quot;,
        ///	&quot;btnCalculate&quot;: &quot;Calculate&quot;,
        ///	&quot;lblCalculating&quot;: &quot;Drag and drop files here...&quot;,
        ///	&quot;lblCalculatingNow&quot;: &quot;Calculating...&quot;,
        ///	&quot;btnCancelHashing&quot;: &quot;Cancel&quot;,
        ///	&quot;btnCancelHashingPressed&quot;: &quot;Cancelling...&quot;,
        ///	&quot;button7&quot;: &quot;OK&quot;,
        ///	&quot;label1&quot;: &quot;Expected hash:&quot;,
        ///	&quot;btnPaste&quot;: &quot;Paste&quot;,
        ///	&quot;chkRemove&quot;: &quot;Remove dashes&quot;,
        ///	&quot;label2&quot;: &quot;Resul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hashing {
            get {
                object obj = ResourceManager.GetObject("hashing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
